### ISSUE TITLE
在cs全屏模式中，原神已经启动，但是没有置顶

### ISSUE THREAD

**Issue by craaaaaa** [AuroraZiling/GenshinImpact_Start_CSharpRemake#1]

**Comment by AuroraZiling** [comment]
在闪光后尝试不做任何操作，静等一会看看会不会置顶
这是目前的一个bug（）

**Comment by craaaaaa** [comment]
那我再试试

**Comment by craaaaaa** [comment]
成功了，但是能不能检测到屏幕白屏后直接用白色背景置顶直到原神窗口弹出后再关闭白色背景呢？

**Comment by AuroraZiling** [comment]
在这么写

**Comment by craaaaaa** [comment]
成功了，但是能不能检测到屏幕白屏后直接用白色背景置顶直到原神窗口弹出后再关闭白色背景呢？（启动时间有点长）

**Comment by AuroraZiling** [comment]
[net7.0-windows.zip](https://github.com/AuroraZiling/GenshinImpact_Start_CSharpRemake/files/12428707/net7.0-windows.zip)
试一下能不能做到闪光后持续白屏，然后到原神启动
我这边没啥问题
